### ISSUE TITLE
How to Run

### ISSUE THREAD

**Issue by tdchen5** [haoliangyu/angular2-leaflet-starter#24]
I have just started looking into leaflet, TypeScript, and Angular 2, and I am used to being able to run an application by typing "npm start" in the terminal. This does not work for me.

I have already typed in "npm install" and "webpack" but am unsure if that is correct and what to do from there.

**Comment by Bilal-io** [comment]
What you need to do after running `webpack` is to go a folder called public, open the index.html file in the browser. If you make updates, you'll have to run `webpack` again to recompile. 
A better way is to use [webpack-dev-serve](http://webpack.github.io/docs/webpack-dev-server.html) in order to serve the project on `http://localhost:8080`

**Comment by haoliangyu** [comment]
@Bilal-io Thank you for your answer!

@tdchen5 More specifically, the compiled files are at `public` folder, which is automatically created by the command `webpack`. Please open the `index.html` there, not the one in the `public_src` folder.

**Comment by tdchen5** [comment]
Thank you for the prompt answer!
